#include <gtest/gtest.h>
#include <ROOT/RNTupleReader.hxx>
#include <memory>
#include <vector>
#include <utility>
#include "Utils.hpp"

TEST(SplitRangeByClustersIntegration, RealROOTFile) {
    // Open the test ROOT file generated by gen_test_rootfile
    auto reader = ROOT::RNTupleReader::Open("hits", "test_file.root");
    ASSERT_TRUE(reader);

    // Call the function under test
    auto chunks = Utils::split_range_by_clusters(reader.get(), 2);

    // We expect 2 chunks, with boundaries (0, 512) and (512, 1000)
    ASSERT_EQ(chunks.size(), 2);
    EXPECT_EQ(chunks[0], std::make_pair(0ul, 512ul));
    EXPECT_EQ(chunks[1], std::make_pair(512ul, 1000ul));
} 